-- =====================================================
-- 鑫速录-企业财务报表自动化填报与智能分析系统
-- 数据库初始化脚本 (H2 Database 兼容版本)
-- 创建时间: 2026-07-16
-- =====================================================

-- 1. 用户表（使用sys_user避免H2保留关键字冲突）
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(100),
    email VARCHAR(100),
    phone VARCHAR(20),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    status INTEGER NOT NULL DEFAULT 1,
    last_login_time TIMESTAMP,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_sys_user_username ON sys_user(username);
CREATE INDEX idx_sys_user_status ON sys_user(status);

-- 2. 企业表
CREATE TABLE IF NOT EXISTS enterprise (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_name VARCHAR(200) NOT NULL,
    enterprise_code VARCHAR(50) UNIQUE,
    industry VARCHAR(100),
    legal_person VARCHAR(100),
    registered_capital DECIMAL(18,2),
    establish_date DATE,
    address VARCHAR(500),
    contact_person VARCHAR(100),
    contact_phone VARCHAR(20),
    risk_level VARCHAR(20) DEFAULT 'NORMAL',
    health_score INTEGER,
    last_report_date DATE,
    manager_name VARCHAR(100),
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_enterprise_created_by FOREIGN KEY (created_by) REFERENCES sys_user(id)
);

CREATE INDEX idx_enterprise_name ON enterprise(enterprise_name);
CREATE INDEX idx_enterprise_code ON enterprise(enterprise_code);
CREATE INDEX idx_enterprise_risk_level ON enterprise(risk_level);

-- 3. 财务报表归档表
CREATE TABLE IF NOT EXISTS financial_report_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id BIGINT NOT NULL,
    report_type VARCHAR(30) NOT NULL,
    report_period VARCHAR(20) NOT NULL,
    report_year INTEGER NOT NULL,
    report_quarter INTEGER,
    report_month INTEGER,
    filing_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    validation_status VARCHAR(20),
    total_assets DECIMAL(18,2),
    total_liabilities DECIMAL(18,2),
    total_equity DECIMAL(18,2),
    revenue DECIMAL(18,2),
    net_profit DECIMAL(18,2),
    operating_cash_flow DECIMAL(18,2),
    data_source VARCHAR(50),
    data_quality_score DECIMAL(5,2),
    remarks TEXT,
    manager_name VARCHAR(100),
    uploaded_by BIGINT,
    reviewed_by BIGINT,
    reviewed_time TIMESTAMP,
    review_comment TEXT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_archive_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprise(id),
    CONSTRAINT fk_archive_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES sys_user(id),
    CONSTRAINT fk_archive_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES sys_user(id)
);

CREATE INDEX idx_archive_enterprise_id ON financial_report_archive(enterprise_id);
CREATE INDEX idx_archive_status ON financial_report_archive(filing_status);
CREATE INDEX idx_archive_date ON financial_report_archive(report_year, report_quarter, report_month);

-- 4. 上传文件表
CREATE TABLE IF NOT EXISTS uploaded_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255),
    file_path VARCHAR(500) NOT NULL,
    file_size BIGINT NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    mime_type VARCHAR(100),
    md5_hash VARCHAR(32),
    upload_status VARCHAR(20) NOT NULL DEFAULT 'UPLOADED',
    ocr_task_id BIGINT,
    uploaded_by BIGINT NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_file_archive FOREIGN KEY (archive_id) REFERENCES financial_report_archive(id),
    CONSTRAINT fk_file_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES sys_user(id)
);

CREATE INDEX idx_file_archive_id ON uploaded_file(archive_id);
CREATE INDEX idx_file_upload_time ON uploaded_file(created_time);

-- 5. OCR任务表
CREATE TABLE IF NOT EXISTS ocr_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL,
    task_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    task_type VARCHAR(30) NOT NULL,
    provider VARCHAR(30) DEFAULT 'http',
    total_fields INTEGER DEFAULT 0,
    recognized_fields INTEGER DEFAULT 0,
    high_confidence_count INTEGER DEFAULT 0,
    medium_confidence_count INTEGER DEFAULT 0,
    low_confidence_count INTEGER DEFAULT 0,
    average_confidence DECIMAL(7,4),
    processing_time_ms INTEGER,
    error_message TEXT,
    result_summary TEXT,
    source_enterprise_name VARCHAR(200),
    source_report_period VARCHAR(20),
    source_report_date DATE,
    source_unit VARCHAR(20),
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_by BIGINT NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_ocr_task_file FOREIGN KEY (file_id) REFERENCES uploaded_file(id),
    CONSTRAINT fk_ocr_task_created_by FOREIGN KEY (created_by) REFERENCES sys_user(id)
);

CREATE INDEX idx_ocr_task_file_id ON ocr_task(file_id);
CREATE INDEX idx_ocr_task_status ON ocr_task(task_status);

-- 6. OCR识别字段结果表
CREATE TABLE IF NOT EXISTS ocr_field_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ocr_task_id BIGINT NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    field_code VARCHAR(50),
    field_value VARCHAR(500),
    secondary_value VARCHAR(500),
    tertiary_value VARCHAR(500),
    numeric_value DECIMAL(18,2),
    confidence_score DECIMAL(7,4) NOT NULL,
    confidence_level VARCHAR(20),
    field_type VARCHAR(30),
    is_reviewed INTEGER DEFAULT 0,
    reviewed_value DECIMAL(18,2),
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    review_comment VARCHAR(500),
    bounding_box VARCHAR(200),
    page_number INTEGER DEFAULT 1,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_ocr_result_task FOREIGN KEY (ocr_task_id) REFERENCES ocr_task(id)
);

CREATE INDEX idx_ocr_result_task_id ON ocr_field_result(ocr_task_id);
CREATE INDEX idx_ocr_result_confidence ON ocr_field_result(confidence_score);
CREATE INDEX idx_ocr_result_reviewed ON ocr_field_result(is_reviewed);

-- 7. 资产负债表主表
CREATE TABLE IF NOT EXISTS balance_sheet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT NOT NULL,
    enterprise_id BIGINT NOT NULL,
    report_period VARCHAR(20) NOT NULL,
    report_date DATE NOT NULL,
    total_current_assets DECIMAL(18,2),
    total_non_current_assets DECIMAL(18,2),
    total_assets DECIMAL(18,2),
    total_current_liabilities DECIMAL(18,2),
    total_non_current_liabilities DECIMAL(18,2),
    total_liabilities DECIMAL(18,2),
    total_equity DECIMAL(18,2),
    balance_check_result VARCHAR(20),
    balance_difference DECIMAL(18,6),
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_bs_archive FOREIGN KEY (archive_id) REFERENCES financial_report_archive(id),
    CONSTRAINT fk_bs_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprise(id)
);

CREATE INDEX idx_bs_archive_id ON balance_sheet(archive_id);
CREATE INDEX idx_bs_date ON balance_sheet(report_date);

-- 8. 资产负债表明细项表
CREATE TABLE IF NOT EXISTS balance_sheet_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance_sheet_id BIGINT NOT NULL,
    item_code VARCHAR(50),
    item_name VARCHAR(100) NOT NULL,
    item_category VARCHAR(30),
    ending_balance DECIMAL(18,2),
    beginning_balance DECIMAL(18,2),
    change_amount DECIMAL(18,2),
    change_percentage DECIMAL(10,4),
    sort_order INTEGER,
    is_total_row INTEGER DEFAULT 0,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_bsi_sheet FOREIGN KEY (balance_sheet_id) REFERENCES balance_sheet(id)
);

CREATE INDEX idx_bsi_sheet_id ON balance_sheet_item(balance_sheet_id);

-- 9. 利润表主表
CREATE TABLE IF NOT EXISTS income_statement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT NOT NULL,
    enterprise_id BIGINT NOT NULL,
    report_period VARCHAR(20) NOT NULL,
    report_date DATE NOT NULL,
    total_revenue DECIMAL(18,2),
    total_cost DECIMAL(18,2),
    operating_profit DECIMAL(18,2),
    profit_before_tax DECIMAL(18,2),
    net_profit DECIMAL(18,2),
    gross_profit_rate DECIMAL(10,4),
    net_profit_rate DECIMAL(10,4),
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_is_archive FOREIGN KEY (archive_id) REFERENCES financial_report_archive(id),
    CONSTRAINT fk_is_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprise(id)
);

CREATE INDEX idx_is_archive_id ON income_statement(archive_id);
CREATE INDEX idx_is_date ON income_statement(report_date);

-- 10. 利润表明细项表
CREATE TABLE IF NOT EXISTS income_statement_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    income_statement_id BIGINT NOT NULL,
    item_code VARCHAR(50),
    item_name VARCHAR(100) NOT NULL,
    item_category VARCHAR(30),
    current_period_amount DECIMAL(18,2),
    previous_period_amount DECIMAL(18,2),
    monthly_amount DECIMAL(18,2),
    change_amount DECIMAL(18,2),
    change_percentage DECIMAL(10,4),
    sort_order INTEGER,
    is_total_row INTEGER DEFAULT 0,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fki_statement FOREIGN KEY (income_statement_id) REFERENCES income_statement(id)
);

CREATE INDEX fki_statement_id ON income_statement_item(income_statement_id);

-- 11. 现金流量表主表
CREATE TABLE IF NOT EXISTS cash_flow_statement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT NOT NULL,
    enterprise_id BIGINT NOT NULL,
    report_period VARCHAR(20) NOT NULL,
    report_date DATE NOT NULL,
    net_operating_cash_flow DECIMAL(18,2),
    net_investing_cash_flow DECIMAL(18,2),
    net_financing_cash_flow DECIMAL(18,2),
    net_increase_in_cash DECIMAL(18,2),
    beginning_cash_balance DECIMAL(18,2),
    ending_cash_balance DECIMAL(18,2),
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_cfs_archive FOREIGN KEY (archive_id) REFERENCES financial_report_archive(id),
    CONSTRAINT fk_cfs_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprise(id)
);

CREATE INDEX idx_cfs_archive_id ON cash_flow_statement(archive_id);
CREATE INDEX idx_cfs_date ON cash_flow_statement(report_date);

-- 12. 现金流量表明细项表
CREATE TABLE IF NOT EXISTS cash_flow_statement_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id BIGINT NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    item_code VARCHAR(50),
    item_type VARCHAR(30), -- OPERATING, INVESTING, FINANCING
    row_number INTEGER,
    amount DECIMAL(18,2),
    current_period_amount DECIMAL(18,2),
    previous_period_amount DECIMAL(18,2),
    monthly_amount DECIMAL(18,2),
    notes VARCHAR(500),
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fkcsi_statement FOREIGN KEY (statement_id) REFERENCES cash_flow_statement(id)
);

CREATE INDEX idxcsi_statement_id ON cash_flow_statement_item(statement_id);

-- 13. 字段映射规则表
CREATE TABLE IF NOT EXISTS field_mapping_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_field_name VARCHAR(200) NOT NULL,
    target_field_name VARCHAR(100) NOT NULL,
    source_table VARCHAR(50),
    target_table VARCHAR(50),
    field_alias VARCHAR(200),
    unit VARCHAR(20),
    data_type VARCHAR(30),
    conversion_formula VARCHAR(500),
    priority INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    description VARCHAR(500),
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_fmr_source ON field_mapping_rule(source_field_name);
CREATE INDEX idx_fmr_target ON field_mapping_rule(target_field_name);

-- 14. 财务指标定义表
CREATE TABLE IF NOT EXISTS financial_indicator (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_code VARCHAR(50) NOT NULL UNIQUE,
    indicator_name VARCHAR(100) NOT NULL,
    category VARCHAR(30) NOT NULL, -- SOLVENCY, PROFITABILITY, OPERATION, CASH_FLOW, GROWTH
    unit VARCHAR(20),
    formula TEXT,
    description TEXT,
    normal_range_min DECIMAL(10,4),
    normal_range_max DECIMAL(10,4),
    warning_threshold_low DECIMAL(10,4),
    warning_threshold_high DECIMAL(10,4),
    calculation_order INTEGER,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_fi_category ON financial_indicator(category);
CREATE INDEX idx_fi_code ON financial_indicator(indicator_code);

-- 15. 财务指标值表
CREATE TABLE IF NOT EXISTS financial_indicator_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT,
    enterprise_id BIGINT NOT NULL,
    indicator_code VARCHAR(50) NOT NULL,
    indicator_name VARCHAR(100),
    category VARCHAR(30),
    "value" DECIMAL(18,4),
    unit VARCHAR(20),
    status VARCHAR(20),
    threshold_min DOUBLE,
    threshold_max DOUBLE,
    calculation_detail VARCHAR(1000),
    calculated_time TIMESTAMP,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fiv_report FOREIGN KEY (report_id) REFERENCES financial_report_archive(id),
    CONSTRAINT fiv_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprise(id)
);

CREATE INDEX idx_indicator_report ON financial_indicator_value(report_id, indicator_code);

-- 16. 财务健康评分表
CREATE TABLE IF NOT EXISTS financial_health_score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT,
    enterprise_id BIGINT NOT NULL,
    report_date DATE,
    total_score DECIMAL(5,2),
    solvency_score DECIMAL(5,2),
    profitability_score DECIMAL(5,2),
    cash_flow_score DECIMAL(5,2),
    operation_score DECIMAL(5,2),
    growth_score DECIMAL(5,2),
    risk_level VARCHAR(20),
    solvency_weight DECIMAL(3,2),
    profitability_weight DECIMAL(3,2),
    cash_flow_weight DECIMAL(3,2),
    operation_weight DECIMAL(3,2),
    growth_weight DECIMAL(3,2),
    summary VARCHAR(2000),
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fhs_report FOREIGN KEY (report_id) REFERENCES financial_report_archive(id),
    CONSTRAINT fhs_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprise(id)
);

CREATE INDEX idx_health_score_enterprise ON financial_health_score(enterprise_id, report_date);

-- 17. 财务分析报告表
CREATE TABLE IF NOT EXISTS financial_analysis_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT,
    enterprise_id BIGINT,
    report_title VARCHAR(200),
    report_type VARCHAR(50),
    executive_summary TEXT,
    overall_assessment TEXT,
    key_findings TEXT,
    risk_analysis TEXT,
    positive_factors TEXT,
    improvement_suggestions TEXT,
    data_quality_notes TEXT,
    generation_method VARCHAR(50),
    status VARCHAR(20) DEFAULT 'DRAFT',
    version INTEGER DEFAULT 1,
    created_by VARCHAR(50),
    submitted_by VARCHAR(50),
    submitted_time TIMESTAMP,
    approved_by VARCHAR(50),
    approved_time TIMESTAMP,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT far_report FOREIGN KEY (report_id) REFERENCES financial_report_archive(id),
    CONSTRAINT far_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprise(id)
);

-- 18. 历史指标趋势数据表
CREATE TABLE IF NOT EXISTS historical_indicator_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id BIGINT NOT NULL,
    indicator_code VARCHAR(50) NOT NULL,
    indicator_name VARCHAR(100),
    category VARCHAR(30),
    report_period VARCHAR(20),
    report_date DATE,
    indicator_value DECIMAL(18,4),
    unit VARCHAR(20),
    period_type VARCHAR(10),
    "year" INTEGER,
    quarter INTEGER,
    change_rate DECIMAL(10,4),
    year_on_year_change DECIMAL(10,4),
    trend_direction VARCHAR(10),
    source_report_id BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fhiv_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprise(id),
    CONSTRAINT fhiv_report FOREIGN KEY (source_report_id) REFERENCES financial_report_archive(id)
);

CREATE INDEX idx_historical_enterprise ON historical_indicator_value(enterprise_id);
CREATE INDEX idx_historical_indicator ON historical_indicator_value(indicator_code);

-- 19. 审计日志表
CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(50),
    target_id BIGINT,
    details TEXT,
    ip_address VARCHAR(50),
    user_agent VARCHAR(500),
    result VARCHAR(20) DEFAULT 'SUCCESS',
    error_message TEXT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_audit_username ON audit_log(username);
CREATE INDEX idx_audit_action ON audit_log(action);
CREATE INDEX idx_audit_time ON audit_log(created_time);
